### ISSUE TITLE
Option for auto-save

### ISSUE THREAD

**Issue by stevage** [jaredwray/flat-cache#105]
Consider an option that automatically persists every change:

```
const cache = flatCache.load('cacheId', path.resolve('./path/to/folder'), { autoSave: true });
```

**Comment by jaredwray** [comment]
@stevage - we haven’t seen any traction on this request so will close it out. If you want to contribute this feature you can as PRs are welcome!

**Comment by felixsebastian** [comment]
why not tho

**Comment by jaredwray** [comment]
Check out the latest at https://github.com/jaredwray/cacheable/tree/main/packages/flat-cache
