### ISSUE TITLE
Add repo migration notice to README

### ISSUE THREAD

**Issue by jnoordsij** [jaredwray/flat-cache#107]
When looking for the source of the package, I ran into this repo and was a little confused about it lacking the code for the `v6` release. Upon further inspection I noticed that this was released through https://github.com/jaredwray/cacheable/commit/00bfef32b82a48e43a2faf971577f808dd0de1f7.

For future reference, it would be nice to have a clear warning in the README pointing to the new location for release of version 6 and up.

**Comment by jaredwray** [comment]
@jnoordsij - I will be removing this repo this month which should solve the issue. Sorry for the confusion!
