### ISSUE TITLE
ClearAll not working

### ISSUE THREAD

**Issue by morwalz** [jaredwray/flat-cache#21]
Hi Function clear all not working

**Comment by royriojas** [comment]
Sorry somehow this issue went unnoticed. Do you think you can provide a repro case of this issue?

I noticed there is no test covering `clearAll` so it might actually be happening.

**Comment by fazulk** [comment]
I noticed the function removes the file, But somehow   cache.getKey(key) is still able to locate the key in memory.

**Comment by aryak93** [comment]
Please fix this as soon as possible.

**Comment by morwalz** [comment]
@royriojas It is simple. this function at all does not work

**Comment by nysky1** [comment]
Doesn't this pretty much ruin the module?

**Comment by vndevil** [comment]
You have to provide folder cache path, example:

```
const flatCache = require('flat-cache');
const flatCacheFolderPath = './src/Server/Config/_flat-cache';
...
flatCache.clearAll(flatCacheFolderPath); // remove the cache directory
```

**Comment by Andrea2099** [comment]
> I noticed the function removes the file, But somehow cache.getKey(key) is still able to locate the key in memory.


It depends where you declare the file loading, if it is in the module node js instantiates it only one time!
