### ISSUE TITLE
Remove dependency on `graceful-fs`

### ISSUE THREAD

**Issue by royriojas** [jaredwray/flat-cache#27]
Since we only use `fs.existsSync` from that package and that checking for existence should be done now using `fs.statSync` we should just align and remove the dependency as well.

**Comment by jimmywarting** [comment]
I don't see graceful-fs being used in the code anywhere, still relevant?

**Comment by royriojas** [comment]
Probably not. If not actually used it can be removed.

Roy Ronald Riojas Montenegro

**Comment by jimmywarting** [comment]
don't see any graceful-fs being used anywhere in this repo. can probably close this issue
