### ISSUE TITLE
Clear Cache

### ISSUE THREAD

**Issue by SirPhemmiey** [jaredwray/flat-cache#41]
When do i clear the cache?

I manually added a new row to a table and when I called the end point, it still showed me the old rows. So at what point do I clear the cache?

**Comment by kaoz70** [comment]
You would have to clear the cache at some point in your app flow, for example on any CRUD operation, or add a button to the app's admin UI that sends a request to delete the cache. It's really up to you when and how to do this.

**Comment by jaredwray** [comment]
There is a clearall function but we are going to be adding more tests around this.
