### ISSUE TITLE
Update minimist to 1.2.3 or later

### ISSUE THREAD

**Issue by p1ho** [jaredwray/flat-cache#47]
Hello, just found this out, so wanted to open an issue.

minimist released a security statement to use version 1.2.3 or later due to a [prototype pollution bug](https://www.npmjs.com/package/minimist#security)

minimist is not a top level dependency (It's not in [`package.json`](https://github.com/royriojas/flat-cache/blob/master/package.json)), but it is present in [`package-lock.json`](https://github.com/royriojas/flat-cache/blob/master/package-lock.json#L1458) (a word search reveals 21 occurrences)

This means projects with flat-cache as dependency and a build process that includes checking vulnerability (through `$ npm audit`) might have a fail build because of it. I was wondering if you can please take a look, thanks!

**Comment by jfoclpf** [comment]
Please update the `write` dependency asap to v 2.0.0. That's what is disseminating the vulnerability

**Comment by SuperITMan** [comment]
This should be solved by #46

**Comment by royriojas** [comment]
Is this a real issue? I mean, it is a devDependency for this project, how is it that minimist ended being installed? is it a dependency of flatted or rimraf?

**Comment by SuperITMan** [comment]
Hello @royriojas 

Actually, the description of the issue is not 100% correct. As @jfoclpf mentioned, the dependency `write` of `flat-cache` has be updated to version > 2.0.0 asap. Because

```
flatcache - 2.0.1:
  - write - 1.0.3: 
    - mkdirp - ^0.5.0:
      - minimist - 0.0.8
```

Thanks for your lib 😊

**Comment by yumetodo** [comment]
To update `write` to `>=2.0.0`, please drop support `node.js < 10` and merge #46.

**Comment by jaredwray** [comment]
@yumetodo - we will be removing nodejs 10 support in the upcoming weeks.
