### ISSUE TITLE
remove rimraf?

### ISSUE THREAD

**Issue by jimmywarting** [jaredwray/flat-cache#59]
rimraf comes with a large dependency: https://npmgraph.js.org/?q=flat-cache@3.0.4
maybe should consider dropping it and instead use nodes native [rm](https://nodejs.org/dist/latest-v16.x/docs/api/fs.html#fs_fspromises_rm_path_options), with recursive mode?

Would require node 14.14 doe...

Can make a PR if u like

**Comment by royriojas** [comment]
I always align with the latest version eslint supports, if they also
support node > 14.14, then it might be possible.


Roy Ronald Riojas Montenegro

**Comment by jaredwray** [comment]
@jimmywarting - I am game to remove rimraf with just custom code to do the work.

**Comment by jaredwray** [comment]
@jimmywarting - going to do an minor update supporting 12 so we have that in place for legacy clients. Then the plan is to move this to >=14 over the next couple months. Will remove rimraf then.

**Comment by jaredwray** [comment]
@jimmywarting - The next published release going out (~30 days) will be a major version bum and moving to v14 as the minimum.

**Comment by The-Code-Monkey** [comment]
@jaredwray any update on this?

**Comment by jaredwray** [comment]
we had to wait on this but will make the change on it in January 2024 with a major version bump

**Comment by The-Code-Monkey** [comment]
Ah ok no worries.

**Comment by jaredwray** [comment]
https://github.com/jaredwray/flat-cache/pull/87 has the removal of rimraf as a core dependency

**Comment by jaredwray** [comment]
We will release this in the upcoming month with our standard release schedule.
