### ISSUE TITLE
Switch from cjs to ESM?

### ISSUE THREAD

**Issue by jimmywarting** [jaredwray/flat-cache#60]
Many modules are switching to ESM to support both Deno and browser imports without bundeling. Think you should make the switch as well...

Can make a PR if u like

would require at least node v12.17

**Comment by royriojas** [comment]
Sure that would be nice!


Roy Ronald Riojas Montenegro

**Comment by jimmywarting** [comment]
If you merge #58 than i can have a crack at making a ESM pr and also remove rimraf (if possible)
or do you want separate PR for that? (easier to review)

**Comment by jimmywarting** [comment]
Mather of facts, i think it would be best if you first switch to github actions before i make any PR's ?

**Comment by jaredwray** [comment]
@jimmywarting - we will be updating the actions and code coverage work in the next 2-6 weeks.

**Comment by jaredwray** [comment]
@jimmywarting - we will probably want to move this to some more modern code before. I will ping you after we get that updated first.
