### ISSUE TITLE
Help Maintain this project

### ISSUE THREAD

**Issue by jaredwray** [jaredwray/flat-cache#63]
@royriojas - really love this project and would like to support it in Keyv also. Was wondering if you could contact me to talk about how I can help with this? 

Send me a note at me@jaredwray.com.

**Comment by jaredwray** [comment]
@yeungon - thanks for the thumbs up. Havent heard from @royriojas yet.

**Comment by guilhermehn** [comment]
Are you interested in small PRs with some quality of life changes? I think I can work on #59 and (maybe) #60, but that would increase the required Node version to 14 at least.

**Comment by jaredwray** [comment]
hi @guilhermehn - We will start to get this project updated in the coming weeks. I think right now we are looking to see what version of node needs to be supported as this is pretty old and we want to maintain as much as possible.
