### ISSUE TITLE
Breaking change in a minor version

### ISSUE THREAD

**Issue by ljharb** [jaredwray/flat-cache#80]
v3.0 of flat-cache has `engines.node` set to "^10.12.0 || >=12.0.0", but v3.1.0 sets it to ">=12.0.0", which is a breaking change. (it was broken in #74) This is causing the tests in one of my packages to break.

Please publish a v3 that restores `^10.12.0` compatibility, and then if you'd still like to drop node 10 support a v4 would be perfectly fine. Thanks!

**Comment by ljharb** [comment]
Went ahead and filed #81 in the hopes that that's helpful :-)

**Comment by ljharb** [comment]
Thanks! Much obliged, and i look forward to the release.

**Comment by jaredwray** [comment]
Released. Thanks for the effort on this
