### ISSUE TITLE
[vulnerability] Glob@7.2.3 dependency Inflight@1.0.6 contains memory leak

### ISSUE THREAD

**Issue by rreeves8** [jaredwray/flat-cache#83]
This package should be updated rimraf to version 5.0.5. current rimraf version uses outdated glob that has a dependency with a memory leak. 

Inflight issue
#https://github.com/isaacs/inflight/issues/5

Remix-dev issue
#https://github.com/remix-run/remix/issues/8271

**Comment by jaredwray** [comment]
@rreeves8 we are doing a major version release now to handle this but will require min Nodejs `>=16`

https://github.com/jaredwray/flat-cache/pull/86

**Comment by rreeves8** [comment]
> @rreeves8 we are doing a major version release now to handle this but will require min Nodejs `>=16`
> 
> #86

Great thanks !
