### ISSUE TITLE
Where are the Error Handlers?

### ISSUE THREAD

**Issue by eorroe** [jaredwray/flat-cache#84]
Hey just started using this library.

I am aware you want to keep it simple so may not implement my suggestion.

But where are the error handlers.

```
.setKey()
.save()
```

all return `undefined`
so there is no way to see if the data was saved or not

Would be nice if
- they returned a promise or the data that was saved
- we could pass a callback function for error handlers

I am having trouble debugging my application because of it.

I also searched this repository for "error" so for a module that is downloaded by the millions, I assume there are no errors on the module side and it has to be something in my code.

But still can't debug because of no error handlers.

However my `console.logs` indicate the functions are being called

**Comment by jaredwray** [comment]
@eorroe - Thanks for the note and that is correct that we do not return anything. I do believe as we modernize this code base we will look to do a return of at least true or false. Also, with the major version release we are looking at throwing errors if there is an issue. 

This will most likely happen later in 2024.
