### ISSUE TITLE
How can you change the path where files are saved?

### ISSUE THREAD

**Issue by q351941406** [jaredwray/flat-cache#90]
How can you change the path where files are saved?

**Comment by jaredwray** [comment]
/**
   * Load a cache identified by the given Id. If the element does not exists, then initialize an empty
   * cache storage. If specified `cacheDir` will be used as the directory to persist the data to. If omitted
   * then the cache module directory `./cache` will be used instead
   *
   * @method load
   * @param docId {String} the id of the cache, would also be used as the name of the file cache
   * @param [cacheDir] {String} directory for the cache entry
   */
