### ISSUE TITLE
Why Keyv is necessary?

### ISSUE THREAD

**Issue by NivEz** [jaredwray/flat-cache#94]
I was playing with the package and noticed that it doesn't really use `keyv.get()`, if it is indeed the case, why do we use `keyv.set()` if we won't access the items later on? Maybe I just need more clarification.
The package requires `keyv` and on `load` we initialize a new instance (`new Keyv()`).
In my local machine I commented out all `keyv` occurrences and `flat-cache` worked.

TLDR;
Why is `keyv` necessary? 

Thanks

**Comment by jaredwray** [comment]
Hi. We are slowly moving to using keyv as the main storage adapter for this

**Comment by NivEz** [comment]
Btw, do you need any help with development / code contribution?

**Comment by jaredwray** [comment]
Hi @NivEz - we would love help on this. Currently the plan is to work on modernizing this code base and migrating it to typescript with Keyv as the backend. If you are interested I can start putting out what work needs to be done.

**Comment by NivEz** [comment]
Do you have some checklist / board like this out there so I can see where I can help: https://github.com/jaredwray/keyv/issues/868 ?
I will also have a look at `keyv` where I can contribute.

**Comment by jaredwray** [comment]
@NivEz - I dont at this time as working on v5 right now. Then will be moving to all the caching libraries.
